### ISSUE TITLE
The body should not scroll past the last line

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#109]
There should be empty space after the last line of p.b *only* if all of p.b is shown.

At present, the last line of p.b may be "over scrolled".  Indeed, often only the last (blank!) line of p.b is visible. This is off-putting. At first glace it can appear that body text has disappeared. The only indication that this is not so is the line number.

The scroll wheel can cause over scrolling. Over scrolling can also happen as the result of restoring the vertical scroll bar when revisiting a node.

The vs code console windows show the desired operation. These windows do not allow over scrolling.

**Comment by boltex** [comment]
I think this was fixed with #107  - as the scroll position is now tied to the body gnx as its own 'real' file representation, and is therefore tracked properly by vscode, unless voluntarily set by leointeg, (for example after a 'find-next' operation).
