### ISSUE TITLE
.leojs filetype

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#125]
Idea for a new official file format for Leo itself. Pasting here temporarily as scratch pad: to classify later.

Described as a typescript interface, this is a .leojs JSON Leo file format concept idea to live alongside the standard .leo xml file format. (best read bottom-up)

_(I had this idea while coding 'morejs', the testbed program for isolating and implementing/try concepts for integration of specific behaviors into a vscode extension. Moved it out of it and turned it into a leointeg issue for now)_

```
interface ILeoHeader {
    fileFormat: number;
}

interface IPosition {
    top: number;
    left: number;
    height: number;
    width: number;
}

interface IGlobals {
    bodyOutlineRatio?: number;
    globalWindowPosition?: IPosition;
    globalLogWindowPosition?: IPosition;
}

interface ITNode {
    tx: string;
    body: string;
}

interface IVNode {
    vh?: string;
    a?: string;
    t: string;
    children: IVNode[];
}

export interface ILeoFile {
    leoHeader: ILeoHeader;
    globals: IGlobals;
    vnodes: IVNode[];
    tnodes: ITNode[];
}
```

**Comment by edreamleo** [comment]
I have just reopened [Leo issue #442](https://github.com/leo-editor/leo-editor/issues/442). Supporting json files in Leo makes a lot of sense now that leoInteg 1.0 is near.

**Comment by edreamleo** [comment]
@boltex I suggest defining the 'vnodes' part of the JSON to be a dict whose keys are the gnx's and whose values are body text. In python:
```python
'tnodes': {v.gnx: v._bodyString for v in c.all_unique_nodes()},
```
This would also be easier to use when reading.

**Comment by edreamleo** [comment]
@boltex I also suggest eliminating the 'globals' key entirely. Leo no longer writes these data in .leo files. Instead, Leo caches the data locally. This substantially reduces unwanted diffs.  The fc.leojs_globals method returns an empty dictionary, but disabled code shows how to add the global data.

**Comment by edreamleo** [comment]
Per [Leo issue #442](https://github.com/leo-editor/leo-editor/issues/442) Leo now reads .leojs files of the format described here, with the following changes:

- Leo never writes the globals dict. That is Leo writes `globals: {}`.
- If the globals dict exists, Leo assumes it contains 'top', 'left', 'height' and 'width' keys.
- Leo prefers to use the cache for globalWindowPosition and outline ratios.

See the **scan_leojs_globals** function for exact operation. Imo, there is no need for the globals dict, but I will be happy to change scan_leojs_globals if you like.

**Comment by boltex** [comment]
Leointeg should offer leojs load or save-as option now that Leo supports leojs 'json' file format.

**Comment by boltex** [comment]
Now part of leointeg 1.0
