### ISSUE TITLE
Offer Find-def and Find-var commands (through alt-or-ctrl+click if possible)

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#138]
Perhaps make a symbol-finder service for the "leo-python" fake language.

**Comment by boltex** [comment]
Use this provider (and just return undefined) to know when to trigger a command in leoBridge ... https://code.visualstudio.com/api/references/vscode-api#TypeDefinitionProvider . The undefined result will just make vscode ignore the result and let leointeg perform a refresh cycle when the real find-def/ var is done.

**Comment by edreamleo** [comment]
@boltex Leo uses Ctrl-click, so it would be good to do that if possible.

**Comment by boltex** [comment]
For now - just make the command available through leointeg's commands and through the minibuffer
