### ISSUE TITLE
Upgrade leoBridge server to accept multiple connections

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#14]
Make leoBridge server 'persist' through disconnects and accept multiple connections from the same user/ip for multiple vscode windows instances.

This is not 'multi-user' or 'multi-edition', instead it multi-connection for the same user at the same 'editing point' so that if leoInteg is installed in vscode for a given machine, and it's started (connected to a leobridge server) all of vscode's windows will show the same tree, body simultaneously in a synchronised manner. 

(Leobridges would just run in a single 'user' & single selected 'commander' as usual, but it **gives a copy of its 'json answers' on all connected websockets at once**.)

This implies new functionality, such as:
- Close Leo file ( Overlaps #13 )
- Disconnect
- Kill Server

**Comment by edreamleo** [comment]
@boltex Hmm. I would prefer that you solve this issue at the vs code side. Leo's bridge is designed for very simple operation.

**Comment by boltex** [comment]
@edreamleo I've changed my stance on this issue a while ago but I've just now updated the issue description to reflect this.

 I understand why it raised suspicion with the old intent i had in mind. I also feel it would not have been sustainable nor stable.

**Comment by boltex** [comment]
Maybe just let vscode start its own distinct leobridge server (increment the port # if already taken) and scrap that idea/issue entirely?

**Comment by edreamleo** [comment]
@boltex Yes, that sounds reasonable.

**Comment by edreamleo** [comment]
@boltex Didn't we decide this wasn't necessary?  Shouldn't we close this issue?

**Comment by boltex** [comment]
I've implemented vscode to start its own distinct leobridge server (increment the port # if already taken) - this is live on the dev branch. So I've closed this issue.
