### ISSUE TITLE
print statement does not preserve leading whitespace

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#152]
For example, this print statement in _makePackage:
```
print(f"{self.currentActionId:>3} {self.action or 'No Action':>30} {','.join(list(package.keys()))}", flush=True)
```
produces the following output:

```
Starting server with command: C:\Users\edreamleo\Python\Python39\python.exe c:\leo.repo\leo-editor/leo/core/leoserver.py -p 32125
LeoServer listening on localhost, port  32125. [ctrl+c] to break
1                      No Action id
2                    !open_files total,filename,node,id
3                    !set_config id
4           !get_search_settings searchSettings,id
5                  !get_children children,id
6                      !get_body body,id
7               !get_body_length len,id
8               !get_body_states language,selection,id
9               !get_body_states language,selection,id
10       !get_all_open_commanders files,id
11                      !get_body body,id
12          !set_current_position node,id
```
Note the mis-alignment between lines 9 and 10.

The first 10 lines should have two leading blanks. Lines 10 through 99 should have one leading blank. So the :>3 specifier does nothing, but :>30 does work.

**Comment by boltex** [comment]
@edreamleo 
Saw line 3 in _processServerOutput, so I commented it out:
 **So I consider fixed in branch 'boltex/issue170' and will be part of the new beta** I was supposed to release yesterday _(but fell asleep cause I smoked too much weed celebrating your bday, which will come out tomorrow instead.)_

```
private _processServerOutput(p_data: string): void {
    p_data.toString().split("\n").forEach(p_line =>{
        // p_line = p_line.trim(); // <--- SHOULD NOT TRIM !
        if (p_line) { // * std out process line by line: json shouldn't have line breaks
            if (p_line.startsWith(Constants.SERVER_STARTED_TOKEN)) {
                if (this._resolvePromise && !this._isStarted) {
                    this._isStarted = true;
                    this._resolvePromise(p_line); // * Server confirmed started
                }
            }
            this._leoIntegration.addTerminalPaneEntry(p_line); // Output message anyways
        }
    });
}
```

**Comment by boltex** [comment]
Fixed again in a better way in  branch 'boltex/issue170' . More consistant with consecutive newlines and fancy print outputs.

**Comment by edreamleo** [comment]
On Sat, Aug 14, 2021 at 12:45 AM Felix ***@***.***> wrote:

> @edreamleo <https://github.com/edreamleo>
> Saw line 3 in _processServerOutput, so I commented it out:
> *So I consider fixed in branch 'boltex/issue170' and will be part of the
> new beta* I was supposed to release yesterday *(but fell asleep cause I
> smoked too much weed celebrating your bday, which will come out tomorrow
> instead.)*
>

Bwahahahah.

Edward
