### ISSUE TITLE
Buttons pane may report "no buttons in the outline"

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#164]
Steps to reproduce:

- In vs-code, load a .leo file containing @buttons.
- Close vs-code.
- Reopen vs-code. 
- Start server from terminal, either a vs-code terminal or an external terminal.
  (I can't seem to start the server any other way).
- In vs-code, click the "Connect to server" button.
  You should see the .leo file, as it was last saved.
- Before doing anything else, click the "Leo Buttons" pane.
  **Case 1**: If the "Leo Buttons" pane was initially closed, the message is: 
    "There are no @buttons in this outline".
    Close and reopen the "Leo Buttons". Now you do see the list of buttons.
   **Case 2**: If the "Leo Buttons" pane was saved in the open state:
   You do see the list of buttons after a short delay.

**Comment by boltex** [comment]
So what I gather is that if initially closed, vscode does not deem necessary to populate the panel by 'refreshing' it's content. 

A single closing and re-opening of the panel gives a slap to the face of vscode, and he thinks "Oh sh*t yeah right better refresh that panel". 

In fact, i also noticed this exact problem with other views of other extensions in vscode. (if initially closed, a second fold/unfold is needed to trigger its 'refresh') So my guess is that it's an vscode issue that appeared in the last release.

I'll investigate more and will close this issue after i have a more definitive explanation for this. (i'm 90% sure i'm right)

**Comment by boltex** [comment]
I'll see if I cant go around this issue before mocrosoft fixesd the problem by seeing if i can detect the unfold, and 'force / trigger' a refresh myself!

& Thanks again for trying out leointeg and reporting issues !!
