### ISSUE TITLE
How do you change font settings for the outline?

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#165]
Changing fonts is likely to be one of the first thing a leoInteg user will want to do.

The standard vs-code font settings do work for leoInteg's body pane.

I have not yet found a way to change the settings for headline font!

Would it be possible for the leoInteg settings page to link to the vs-code settings page for fonts?

**Comment by boltex** [comment]
Thanks for reporting issues for leointeg! 

The vscode API is not as garnished and detailed as you might expect. The only possibilities offered for making an outline/tree view are the relationship structure of the nodes, their icons, and label text. (and smaller subtext) Only. See https://code.visualstudio.com/api/extension-guides/tree-view#tree-data-provider where it is clearly explained that only 2 methods are used to build/render the outline (getchildren, to give children list, and getTreeItem to get icon and label text)

So anything else such as color, highlight, font type, font size ect. are related to the chosen 'Theme', or personal user settings.

**For more details about the sidebar font sizes, (where the Leo tree outlines are located), see https://stackoverflow.com/questions/51456526/how-to-change-font-size-in-vs-code-sidebar** 

See also https://code.visualstudio.com/api/extension-capabilities/extending-workbench for a very breif overview of GUI modifications or additions capabilities.

**Comment by edreamleo** [comment]
@boltex Thanks for these links. Imo, leoInteg has got to do more to help the user. For me, this issue should block the release of leoInteg 1.0.

I have reopened this issue instead of creating a new issue so we'll have all of your links readily at hand.

I shall try my hand at some of the workarounds suggested in the links, looking for some way of helping users like me who find small fonts intolerable. Perhaps a "headline zoom" setting.

Just my first thoughts.

**Comment by edreamleo** [comment]
Oh joy.  There is an easy way, as suggested in one of the links above:

- Zoom the entire screen (in or out) until headlines look good.
- Adjust the size of the body font.

Crucially, vs-code remembers the zoom setting on reload! As a result, #168 (Font Panel) need only tell new users of leoInteg how to do this.

**Comment by edreamleo** [comment]
I am going to close this issue. See #168 instead.
