### ISSUE TITLE
Title heading for the body editor displays node's gnx, but should show headline

### ISSUE THREAD

**Issue by tbpassin** [boltex/leointeg#171]
At the top of the body editor panel, leointeg shows an identifier for the node.  It currently shows the node's gnx, which may be helpful for me and maybe Felix but hardly anyone else.  I suggest that the node's headline should be shown there instead.  There might be a case for using the outline filename instead, but the headline is probably OK.

**Comment by boltex** [comment]
>There might be a case for using the outline filename instead

The body pane is implemented as a file system. Uniqueness the body panes content, i.e. the filenames, is acheived 'naturally' by using the gnx's.

The 'gnx' breadcrumb that you see a top the body pane just below 'LEO: BODY' tab label is the filename. it's a vscode feature I have no control on. I also coded that the filename (that same gnx i'm talking about) is omitted in the actual tab, and that a string 'LEO BODY' is preficed in front in its place. giving the result that you see.

So thanks for the suggestion but it's a limit of vscode. Please suggest different approaches  if you have any other implementation ideas for this. (but for now I'll tag this one as a 'wont fix' until there's a way in vsocode's api to make this any different than just an arbitrary tab label decoration and the gnx below as breadcrumbs)

suggestions : disable breadcrumbs, or see if the breadcrumbs can be disabled for specific languages (Leointeg uses custom languages in its body pane: "leobody.plain", "leobody.python", etc... )

**Comment by boltex** [comment]
Since its possible in vscode to change settings so that it applies for particular languages  only, and that leointeg uses custom languages identifiers for its body pane,  "leobody.plain", "leobody.python", etc... , i think think what you brought up may give me ideas for this concept to be applied to other GUI or settings in vscode :) 

so thank you very much for your input!!

**Comment by boltex** [comment]
Maybe I should precise that the 'LEO BODY' string tab prefix is not dynamic. (As I would obviously have made it be the headline)

**Comment by edreamleo** [comment]
@tbpassin Hah. Never noticed that.

**Comment by boltex** [comment]
I'll close this for now - to be reopened if possibilities or new ideas emerge! :)
