### ISSUE TITLE
Minibuffer command list does not show user-added commands

### ISSUE THREAD

**Issue by tbpassin** [boltex/leointeg#173]
**Update**: See [Leo issue 2093](https://github.com/leo-editor/leo-editor/issues/2093).

I have some custom commands that are not bound to keys or buttons.  They do not show up in leointeg's minibuffer command list.  How can I run them without binding them to to a button?

I know that the Bridge code includes lists of commands that are allowed or disallowed.  I can see the sense of that.  But it leaves my own custom commands out in the cold.

**Comment by edreamleo** [comment]
@tbpassin Thanks for creating this issue. I'm not sure the good/bad lists are the culprit, but that's just speculation on my part.

**Comment by boltex** [comment]
@edreamleo 

- The good list only serves as a check that would output a print log about a good command being also in the bad list.
- The bad list is the only one of those 2 lists of string that discriminates. 

 the method in leoserver is called  ​get_all_leo_commands, it's getting its base list from c.commandsDict.

I'm gonna check why / how  at-commands dont end up there. i'm new to those so go ahead if you have thoughts about that ! :)

**Comment by boltex** [comment]
I'll assign it to you - although it should be done in Leo-editor's leoserver.py instead of leointeg ( i might be wrong - feel free to comment or whatever you feel appropriate)

**Comment by tbpassin** [comment]
It is the user-defined command that aren't showing up.  These are ones whose headline starts with _@command_.  I know that commands in specific outline aren't getting listed.  I'm not sure about commands defined in myLeoSettings.leo, but my guess is that they aren't either.

When leointeg sees a headline beginning with @button, it creates a button bound to that command.  So that part works as expected.  When such a button gets pressed, it can fire a user-defined command, and that works.

If @commands get added to the Leo command editbox, it would need to be on a per-outline basis.  I don't know if the current leointeg design can do that or not.

**Comment by edreamleo** [comment]
@boltex I'll do this next. BTW, unless there are serious doubts about a commit, I recommend merging dev into master almost immediately. That way we can all just pull master and be sure that we are getting the latest code.  In other words, I think we should all be testing new code asap. Worst case: we check out a previous rev in master.

**Comment by edreamleo** [comment]
@tbpassin Should be straightforward to fix.

**Comment by edreamleo** [comment]
**Background**: Within Leo itself, commands created by `@button` and `@command` show up in Leo's minibuffer in two ways:

`<Alt-x>@c<tab>` shows all commands defined by `@command` nodes, both local and global.

All such command names start with the prefix `@command-`.

`<Alt-x>@b<tab>` shows all commands defined by `@button` nodes, both local and global.

All such command names start with the prefix `@button-`.

The minibuffer will also show the same commands *without* the `@button-` or `@command-` prefixes.

For example, I have defined (somewhere, it doesn't matter where) @command-join-node-above. This works as expected: `<Alt-x>join<tab>`

The code in Leo to make all this "just work" is probably pretty hairy. Once I figure out how exactly it all does work I'll probably write something like the following:

```python


```

**Comment by edreamleo** [comment]
As a prototype, the following Leonine scripts prints command names, stripped of `@command`, `@button` and vim-mode related commands.
```python
def unique_commands():
    return (z for z in c.commandsDict.keys() if not z.startswith(('@', ':')))
    
g.printObj(sorted(unique_commands()))
```

**Comment by edreamleo** [comment]
@boltex I agree that the new code should be in leoserver.py.

**Comment by edreamleo** [comment]
A trace in server.get_all_leo_commands shows that c.commandsDict contains no entries starting with `@command`. This looks like a bug in either leoserver.py or leoBridge.py. I'm on it.

**Comment by edreamleo** [comment]
**Update**: The bug is entirely in leoserver.py. 

server.__init__ created a *dummy* commander as follows:
```python
self.dummy_c = g.app.newCommander(fileName=None)
```
but the dummy commander created this way never reads settings, so has no chance of knowing about `@command` or `@button` nodes. Instead, server.get_all_leo_commands must use a real commander.

**Comment by edreamleo** [comment]
I am going to close this. However, see #180.
