### ISSUE TITLE
Implement Leo's Nav Tab

### ISSUE THREAD

**Issue by tbpassin** [boltex/leointeg#174]
leointeg has a nice implementation of Leo's Find/Replace pane.  I use the Nav pane much more.  So I'd appreciate having the Nav pane in leointeg.  

It may not be so easy because the Nav pane's results can be clicked on to go to the line with the match, and I don't know how hard that would be to get working in vsc.  It would be a useful feature if it could be done without too much of a headache.

**Comment by edreamleo** [comment]
@tbpassin This issue is a special case of a larger topic that surely we will address after releasing leoInteg 1.0. There are several plugins that add to Leo's gui using Qt. I propose that we choose, say, the top 5 plugins and see how hard it would be to do each.

**Comment by boltex** [comment]
Good idea, but for next version after 1.0 😅

Thanks again @tbpassin for pointing to this great concept!

**Comment by boltex** [comment]
@tbpassin @ar-jan This feature is now functional and being merged into the dev branch. To be finally merged into master and released in leointeg 1.0.7 shortly after Leo 6.6 is released. 😝

**Comment by tbpassin** [comment]
Excellent!  Congratulations!  A lot of work, I know.
