### ISSUE TITLE
Revise the client/server protocol

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#178]
See [Leo PR: #2095](https://github.com/leo-editor/leo-editor/pull/2095).

**Background**

This problem appeared while working on #173. Imo, the problem can not be fixed in leoserver.py. The client/server protocol must be changed.

At present, **server.get_all_leo_commands** returns a lists of dictionaries, each of the form:
```python
{
  "label": command_name,
  "func":  func_name,
  "detail": doc,
}
```
However, for `@command` or `@button` scripts, the func_name will be the name of a *callback* function, which in effect is an anonymous function! The horrendous details are in sc.registerAllCommands (in mod_scripting.py) and also in the AtButtonCallback class, instances of which are (iirc) essentially fancy callbacks.

**Proposal**

1. server.get_all_leo_commands should return dictionaries *without* a "func" key.
2. The client should be able request execution of commands by the name of the *command*, not the name of the *function* that executes the command.
3. The server should continue to support the execution of methods in Leo.

**Discussion**

ekr-server-protocol branch contains the new version of leoserver.py. See [PR #2095](https://github.com/leo-editor/leo-editor/pull/2095).

The leoInteg minibuffer already shows command names, not function names, so very little in leoInteg will have to change.

**Summary**

server.get_all_leo_commands will supply only *command* names. The names of anonymous callback functions are useless!

See the docstring of **server._do_message** for the new protocol.

**Comment by tbpassin** [comment]
This is similar to a capability I came up with in a non-Leo program.  A whole lot of commands are triggered by pushbuttons.  The child window that has the buttons is almost entirely independent, except for having a reference to the dispatcher located in its parent window.  When a button is pressed in the child window, its callback sends back to the dispatcher a string which is the lookup name for the real method.  The dispatcher has a lookup table - a dict, of course, being Python - to dispatch the actual method.

Neither the parent nor the child need to know anything about how the other one implements any of the details.  They only need to know how to send/receive the right string.  It works great for my application, it should work just as well for Leo.

**Comment by boltex** [comment]
Done in dev :) 
Thanks to both @tbpassin & @edreamleo for their insights and support!!
