### ISSUE TITLE
OS X python3 cannot start leoserver.py

### ISSUE THREAD

**Issue by TK-WF** [boltex/leointeg#183]
OSX (10.15.7)
VSCode (latest and greatest)
Leo (latest from devel)
leointeg (downloaded from Felix site)

When I attempt to start the server via VSCode the command errors. Running the command displayed in VSCode Output from Terminal yields the following error output:

```
python3 /Users/yoyo/leo-editor/leo/core/leoserver.py -p 32125
Traceback (most recent call last):
  File "/Users/yoyo/leo-editor/leo/core/leoserver.py", line 22, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
```

**Comment by boltex** [comment]
Thank you for trying out leointeg!! :)

Message says something about the websockets. Are you aware of that requirement?  (see the requirements in the readme file at https://github.com/boltex/leointeg#requirements )

... it basically says the following:

- Having the Websocket Python Library installed.
  _Install with :_ `pip install websockets`\
  (See [websockets.readthedocs.io/en/stable/intro.html](https://websockets.readthedocs.io/en/stable/intro.html))

Please check if you have fulfilled this small requirement and come back here to follow up on this. 
(if you indeed have the websockets python library installed and still get this error then I'll look into it)

Thanks again for trying out leointeg and for reporting your experience here! Much appreciated!

**Comment by TK-WF** [comment]
OK I fulfilled the websockets requirement and am able to start/connect-to the server.

Two notes:

1. After I installed the VSIX, the first information I saw was the "Welcome to LeoInteg" doc that pops up in VSCode (nice touch) but in my case it would have been nice to see a notice about the requirements there.
2. When I start the server the python "Rocket" icon bounces for a few minutes in the Dock but eventually stops - probably out of your control.

I look forward to what I can accomplish with this integration now - Thanks!

**Comment by boltex** [comment]
Thanks! Great suggestions! 

... although i wonder about that rocket thingy... i'm a total python newb, and I've never seen that in vscode... so if you can post a screenshot of that thing? I'd appreciate! (just curious)

Thanks again!

**Comment by TK-WF** [comment]
![image](https://user-images.githubusercontent.com/5385054/127215968-ca0aa91e-2f2b-4df2-bd42-9dd81581db96.png)

**Comment by boltex** [comment]
Thanks!

 (yeah leointeg starts Leo as an external process, and talks with it though websockets, probably why the 'python is running' indicator gets triggered.)

I'll close this issue for now as it's settled - but I will follow your suggestion and add mentions to the websockets requirements at places other than the 'README' such as the leointeg settings panel, etc... 

So thanks again and don't hesitate to post again or ask questions!
