### ISSUE TITLE
Make Leointeg Views Available to Other VSC Extensions

### ISSUE THREAD

**Issue by tbpassin** [boltex/leointeg#192]
VSC has a number of viewing extensions, such as one that renders Restructured Text, and another that renders Markdown.  Some Leo outlines are intended to be seen in a rendered view. It would be very helpful to be able to show a rendered view of a Leo node or subtree in one of these extensions.  It would play (part of) the role of the Viewrendered and Viewrendered3 plugins.

**Comment by edreamleo** [comment]
On Mon, Aug 16, 2021 at 7:48 AM tbpassin ***@***.***> wrote:

> VSC has a number of viewing extensions, such as one that renders
> Restructured Text, and another that renders Markdown. Some Leo outlines are
> intended to be seen in a rendered view. It would be very helpful to be able
> to show a rendered view of a Leo node or subtree in one of these
> extensions. It would play (part of) the role of the Viewrendered and
> Viewrendered3 plugins.
>
Yes.  More generally, after leoInteg 1.0 goes out the door we will want to
consider:

- a possible ecosystem for *leoInteg *plugins.
- which existing *vs-code* plugins might be most useful for leoInteg.

Edward

**Comment by boltex** [comment]
The way forward to have the equivalent in vscode, is to make an @file (or @clean or your favorite leo external file node) and use an existing vscode extension to visualyse it in a panel in vscode. such as markdown files, svg images, etc. (most file formats that can be visualized in Leo alreasdy have visualisations plugins for vscode) 

checkout this screenshot: from left to right: leo outline, leo body, the @clean .md file output and the visualizaion preview.
(Note : everything is updated and changes simultaneously 'live' in any of those 3 panels below )
![Screenshot from 2022-08-27 16-26-07](https://user-images.githubusercontent.com/847716/187046877-13da651d-4298-4cb5-831f-4c6856f00b22.png)

or this .svg icon previewed live in vscode.
![Screenshot from 2022-08-27 16-28-08](https://user-images.githubusercontent.com/847716/187046921-f2c36a74-1fbb-4d0e-be4e-ff5a5ea3e2b7.png)

So i'll close this issue. Feel free to conmment or even re-open it if i totally misunderstood what was implied in the original post by @tbpassin 

Thanks again! :)
