### ISSUE TITLE
The body pane flashes when switching nodes

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#193]
Do this:

- Open a .leo file with leoInteg.
- Open a new file In the vs-code explorer. There will be a tab called "Untitled-1".
- Switch from node to node in the Leo outline, either with a mouse click or (better), with an arrow key.

Every time a new Leo node is selected the "Untitled-1: tab is *briefly* selected before selecting the new node in the "LEO:BODY" tab. This brief (unwanted!) selection briefly replaces the body pane with the (blank) contents of the "Untitled-1" tab.

If there is no other node selected, what appears briefly is the contents of some other pane, or the default vs-code pane (with the big paper-clip icon) in the background.

**Summary**

- Switching Leo nodes causes considerable screen flash, both in the tab bar and in the body area.
- Exactly what appears in the body area depends on what other tabs are active.

Imo, this is not exactly a release blocker, but it is a major hangnail that should be fixed asap.

**Comment by boltex** [comment]
I only rarely get a noticeable flicker, and it's always only for the very first time a body pane is switched from one outline node to another.

All the other times I switch node while working on a project my body pane does not flicker. (with or without many other tabs open, in single or multiple editors opened at the same time in a vscode window.)

Can you provide other details for this behavior (size of body content, what particular leo file, etc...?)

Also, what surprises me is that I didn't change anything in relation to the node or body-switching logic between 0.1.16 and 0.1.17... Could you try to uninstall the latest beta and revert to 0.1.16 and see if you still get that behavior? I'll send you the 0.1.16 vsix file if you don't have it anymore. (I am very curious as to check if you get this behavior with the previous version of leointeg)

**Comment by edreamleo** [comment]
On Tue, Aug 17, 2021 at 8:33 PM Felix ***@***.***> wrote:

> I only rarely get a noticeable flicker, and it's always only for the very
> first time a body pane is switched from one outline node to another.
>
I get it every single time.

I wonder whether a setting (vs-code or leoInteg) may be the difference
between our experiences.

Edward

**Comment by boltex** [comment]
Oops i forgot to update this issue -> As we discussed  workbench.editor.enablePreview has to be enabled to prevent flickers.

Version 0.1.18 from last week fixes this: Automatic detection of VSCode's workbench.editor.enablePreview if its missing/disabled.

So I'll close it for now as this greatly helps circumventing this issue.
