### ISSUE TITLE
Force "workbench.editor.closeOnFileDelete" to true for LeoInteg

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#201]
The "workbench.editor.closeOnFileDelete" should be handled like the "enable previews" and "close empty groups" settings. (see config.ts for how other settings are handled)

**Comment by boltex** [comment]
Needed since vscode 1.60.0 

Note to self: **(Working in 'insiders'edition for leointeg development would prevent those issues!)**

**Comment by edreamleo** [comment]
@boltex Works for me!
