### ISSUE TITLE
 Offer 'Real Clipboard' operations, instead of leo's 'internal' clipboard behavior 

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#21]
Offer 'Real Clipboard' operations, instead of leo's 'internal' clipboard behavior 

Use globals.gui.clipboard and the real clipboard with g.app.gui.getTextFromClipboard()

For pasting, use g.app.gui.replaceClipboardWith(p_realClipboard)

**Comment by edreamleo** [comment]
@boltex See qt_gui.replaceClipboardWith. I'm not aware of any way to improve this Qt code.

**Comment by boltex** [comment]
I'll implement this with the async methods (see how its done in leojs) by grabbing/putting on the real clipboard, and then sending what to copy or paste via the bridge.

This will require a (very small) modification to leoserver.py.

**Comment by boltex** [comment]
Note: While doing this also add feature to send/transmit whole of vnodes/tnodes to 'refresh/replace' the whole leo document, to prepare for leojs front-end future feature.

**Comment by boltex** [comment]
Note to self: This is done in leojs so just copy the mechanism

**Comment by boltex** [comment]
@edreamleo this milestone is now in the dev branch. Thanks for your valuable input on this issue!
