### ISSUE TITLE
Fix comment/code syntax switching with '@' and '@c'

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#228]
Syntax coloring does not seem to work in some languages with Leo's body directives '@' to switch to comments and '@c' to switch back to code.

**Comment by boltex** [comment]
Bug is in leobody.tmLanguage.json : Compare leobody.tmLanguage.json with leobody.c.tmLanguage.json  ( /* ... */ ) to see that the references of '0' should be '1' and the second part of the capture is uneccessary in the regular expression.

**Comment by edreamleo** [comment]
@boltex I have been following your commits with interest :-)

**Comment by boltex** [comment]
oops: just noticed that I need to remove @raw & @end_raw - and also Add @section_delims
