### ISSUE TITLE
Add commands that use the 'marked' property of nodes

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#23]
Commands that use the 'marked' property of nodes:
- copy-marked _Copies all marked nodes as children of a new node._
- diff-marked-nodes
- ~goto-next-marked~
- mark-changed-items
- mark-subheads
- unmark-all
- clone-marked-nodes
- delete-marked-nodes
- move-marked-nodes

**Comment by edreamleo** [comment]
@boltex See my comments to #30.

**Comment by edreamleo** [comment]
Most of these should now work.

**Comment by boltex** [comment]
@edreamleo Yep thanks! only a couple did not match exactly with pascal cased names (diff-marked-nodes -> diffMarked and not diffMarkedNode) but thats it! 

Only #107 remains before the first release as an extension package!  :lion:

**Comment by edreamleo** [comment]
@boltex Hurray!
