### ISSUE TITLE
Refresh state of color-syntaxing if an edit has changed an 'at'-directive

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#230]
When typing or modifying the active text editor, if a line starting with an @ character is changed, refresh the color-syntax decorations (the body states).

**Comment by edreamleo** [comment]
@boltex Great idea.  Leo should do this!

**Comment by edreamleo** [comment]
@boltex See [Leo issue #2328](https://github.com/leo-editor/leo-editor/issues/2328).

**Comment by boltex** [comment]
This issue should also have been closed automatically when it was moved to 'done in master'. 
Probably my issue automation setup that is to blame :)
