### ISSUE TITLE
Have the 'insert node ' right-click context menu command restore selection

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#231]
To be consistent with other right-click commands such as 'mark' or 'clone', etc.

Will have to modify the server for that.

**Comment by boltex** [comment]
To reconsider: maybe inserting at location does mean it should stay there after inserting to write in body pane directly afterwards.

**Comment by boltex** [comment]
Now fixed in leoserver.py on the https://github.com/leo-editor/leo-editor/tree/felix-server4 branch. Will be part of Leo 6.6.3.

**Comment by edreamleo** [comment]
@boltex :-)
