### ISSUE TITLE
Arrow keys bug (not selecting) when navigating a 'hoisted' outline

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#233]
Selection is not set properly when navigating with the keyboard in an hoisted part of the outline

**Comment by boltex** [comment]
Maybe the 'isRoot' flag was wrongly included in the key hash string id for outline node - or something similar is affecting the key hash string 'id' when hoisted.

**Comment by boltex** [comment]
Body pane changes correctly, so its the selection (node id when recealing and setting selection in vscode's tree) that's wrong when hoisted

**Comment by boltex** [comment]
After investigating, bug is in leoIntegration.ts, in method apToLeoNode.

The stack of nodes (in the archived position json) when hoisted past the first level, (not child of the hidden root node) is inconsistent and node ids are based on stack, so after making nodes for the outline to display there is a mismatch of ids when creating the node for the 'reveal' method. (which makes the selection in the tree)

Relevant experimental code in the devel branch at the start of apToLeoNode method in place for now, I'll finish debugging this probably this weekend.

**Comment by boltex** [comment]
Found it: get parent continues past hoisted node. I'll intercept in leointeg's getParent. (no need to modify the server.)

**Comment by edreamleo** [comment]
On Thu, Dec 9, 2021 at 10:36 PM Felix ***@***.***> wrote:

> Found it: get parent continues past hoisted node. I'll intercept in
> leointeg's getParent. (no need to modify the server.)
>
Oh good.  Do you anticipate any changes to the server in the near future?

Edward

**Comment by boltex** [comment]
@edreamleo oh well.. I talked too fast: I just did add a new feature to the server! 

But I wont add more until you release 6.6 as I need people to update their Leo before I can add those cool new features to LeoInteg ! 😁

**Comment by edreamleo** [comment]
On Fri, Dec 10, 2021 at 10:07 PM Felix ***@***.***> wrote:

> @edreamleo <https://github.com/edreamleo> oh well.. I talked too fast: I
> just did add a new feature to the server!
>
> But I wont add more until you release 6.6 as I need people to update their
> Leo before I can add those cool new features to LeoInteg ! 😁
>
I am preparing to go south for about two months, and don't plan to release
6.6b2 until I get back.

So feel free to change the server as you like.  Will that plan for you?

Edward

**Comment by boltex** [comment]
@edreamleo  No problem :)

**Comment by boltex** [comment]
Fixes have been merged in master
