### ISSUE TITLE
Disable a pop-up message about not supported language (fortran90) & add support for this language

### ISSUE THREAD

**Issue by ATikhonov2** [boltex/leointeg#242]
I'm fine with little support of Fortran in Leo, but the message appears each time I move to a different node and becomes a little bit annoying. I think it would be enough to read the message once during a session )

**Comment by boltex** [comment]
Thank you @ATikhonov2 for finding this!

Indeed I could reproduce by selecting nodes with @language somewhere up in their lineage.

This does nothing in the original Leo so it's clearly a bug.

**Comment by boltex** [comment]
I'll add fortran support while I'm at it.

**Comment by ATikhonov2** [comment]
Thanks, Felix! It might help me to popularize LeoInteg in my team ))

**Comment by boltex** [comment]
Done on the dev branch. I'll publish a new version of leointeg (1.0.6) with full fortran (fixed pos) and fortran90 (free) color-syntaxing and code snippets support  in 24-48 hours.

**Comment by ATikhonov2** [comment]
You don't have to apologize - I appreciate your work. Do it as it fits your timeline.
