### ISSUE TITLE
Make more clear the complain about missing leoID.txt

### ISSUE THREAD

**Issue by ATikhonov2** [boltex/leointeg#248]
I noticed that LeoInteg displays an error on a fresh machine - I installed git, Python, cloned LeoEditor's code, installed VSCode, downloaded and started LeoInteg, and it displayed a message:

![image](https://user-images.githubusercontent.com/20832685/157246736-e179b10e-653a-46ec-8a78-89da76864725.png)

The reason becomes clear when the LeoEditor is launched:
![image](https://user-images.githubusercontent.com/20832685/157247006-0618e879-5c47-4afc-9a09-69b51f705c71.png)

I wonder whether it is possible to create the ID file using just LeoInteg?

PS: Felix, I cannot continue to sponsor your noticeable work because of the sanctions against my country. I'm looking for other ways to express my appreciation for your contribution to Open Source but, honestly, don't see many...

**Comment by boltex** [comment]
Thank you @ATikhonov2 !! Very good find. I'll think about ways to get a valid leoID going if that file is missing. I'll probably just mimic this dialog, and write a leoId.txt file just like leo does before starting the server.

Thanks again and don't worry for the support, and be careful my friend !!

**Comment by boltex** [comment]
@ATikhonov2 I'm gonna ask @edreamleo if he thinks this could be appeased temporarily with a proper error message and clean exit from leoApp.py in Leo itself.

**Comment by ATikhonov2** [comment]
Hi! Thanks for you attention!

I don't see why Edward would reject your proposal, but I'm not an expert in Leo code either)

I'm looking to popularize LeoInteg within my team. My teammates use VSCode a lot (who don't?) - if I tell them there is a magic extension, they would give it a try, but they will resist for sure if I tell them to run the vanilla Leo Editor - it would be to much )) This kind of errors might be discouraging for newbies.

**Comment by boltex** [comment]
@ATikhonov2 I'm in the same position as you! 

(You better wait until leointeg is more stable in a couple months before using it at work/production environment : I still got to redo the tree model, like the one I made in leojs, to eliminate some rare tree rendering fails.)

In the meantime, Edward has added proper exit messages for when the LeoId is not available (Leo tries first to get the O.S. logged user, the Environmenet leoid variable, or, the .leoid.txt file. if all 3 are not available then quitting is done by showing a proper message with standard Leo, and in leoserver / leointeg it just leaves the id to 'None' without crashing.

No more server crashes : I'll be adding soon a dialog in leointeg to set leoid when 'None' / not detected, and release leointeg 1.0.7 very soon :)

Thanks again for your testing and reporting!!

**Comment by boltex** [comment]
@ATikhonov2  The dev branch of leointeg now detects missing leoID, and offers input to the user to set it for the duration of the session, and confirms with a dialog to save it to .leoID.txt for permanent use.

The Leo id is now detectable only with the new leo server, from leo 6.6 final to come out tomorrow... So I'll wait till then to release leointeg 1.0.7, with this new feature (and the new goto&nav panels!)

Thanks again for this great feature suggestion!
