### ISSUE TITLE
Offer to override CTRL+P to goto any node (by headline search) when leo pane focused

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#273]
When a leoInteg panel has focus, replace and mimic vscode's own ctrl+p behavior to select a node instead of opening any file in the workspace. 

**May need a new server method to be added**

Similar to typing in the nav search input, but only for headline. (selects & reveals the position on enter. cancels with escape, or focus out)

Let it be configurable with a simple checkbox option setting for the user to turn off if desired.

**Comment by edreamleo** [comment]
@boltex Feel free to enhance the server. The next release of Leo can come this year if you like.

**Comment by boltex** [comment]
@edreamleo I looked at the server's available methods, and I think i'm ok with the existing 'get_position_data' that's already there.

**Comment by edreamleo** [comment]
On Sat, Dec 3, 2022 at 8:43 PM Felix ***@***.***> wrote:

> @edreamleo <https://github.com/edreamleo> I looked at the server's
> available methods, and I think i'm ok with the existing 'get_position_data'
> that's already there.
>
Thanks for the heads up.

I'm working on better support for running Python's black formatter on files
with Leo sentinels. Any mistakes changing Leo's read/write code would be
disastrous, so it will be good to have an extended period of testing.

Edward
