### ISSUE TITLE
add leointeg to Open-VSX for Theia, VSCodium and other alternate editors

### ISSUE THREAD

**Issue by kghenderson** [boltex/leointeg#284]
https://open-vsx.org/ maintains a list of open visual-studio code
Leo integration should be added here as well (I can probably do this if it's okay with you)

**Comment by boltex** [comment]
@kghenderson Thank you for making me aware of this! I skimmed over the instructions for adding LeoInteg to this registry and I plan to do it relatively shortly! 

Thanks again!!

**Comment by kghenderson** [comment]
cool, np, i just stumbled on this project but it looks very interesting

**Comment by boltex** [comment]
@kghenderson I'm moving forward with this, the process is started and going along well, I registered, followed the steps to be able to publish there, claimed the namespace, etc... (https://github.com/EclipseFdn/open-vsx.org/issues/1648 ) 

I'll try to get it published on this platform for the LeoInteg 1.0.12 release this friday! march 3rd right after the release of Leo 6.7.2 
 :) 

Thanks for inciting me to publish on this platform too!! Hoping this will get even more people to try LeoInteg, (and LeoJS also relatively soon!)

Félix

**Comment by boltex** [comment]
@kghenderson Thanks to the suggestion you've made, leointeg is now on the open-vsx market at https://open-vsx.org/extension/boltex/leointeg!
