### ISSUE TITLE
Add "Search in leo outline" functionality

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#36]
Along with "prev", "next" controls, etc.

**Comment by edreamleo** [comment]
@boltex Are you talking about the quicksearch plugin?

**Comment by boltex** [comment]
@edreamleo Nope, I have no knowledge of a quicksearch plugin in leo. 

I meant just the concept of hitting CTRL+F in a body pane or outline, to have a prompt popup and query me for a text input, upon which a panel under leo's outline, akin to the leo Documents view, wowuld appear, and contrain 2 buttons, prev and next, to cycle like the regular search pane in Leo.. . simplest implementation that comes up to my mind.. .but i havent put much thought in this one...
--
Félix

**Comment by edreamleo** [comment]
@boltex Thanks for the clarification.
