### ISSUE TITLE
Have node selection reflect in body with arrow keys alone, instead of having to use the enter key

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#43]
Suggested by @ar-jan  as an unrelated idea to an other issue #32 : https://github.com/boltex/leointeg/issues/32#issuecomment-636316079
 
Could this be mimicked? ...In Leo, if arrow keys are used in the outline, the node selection is reflected instantly in the body pane. In vscode, an outline has a cursor 

Q&A below: 

Q: It's already the case when using the keyboard to expand/contract nodes so why not making it so too when moving the outline "cursor" ? 
A: expanding and collapsing nodes have an associated event, although moving the cursor in the tree is detectable, the selection cursor is unkown as far as I know as opposed to a collapse/expand event.

**Comment by boltex** [comment]
MIGHT BE POSSIBLE : Just hook on "up down left right" key presses with 'when' condition of having focus on the outline exclusively. -> On leo's side, mae available commands for select up down left and right of current selection. 

In theory.... vs in practice ... 'know what i mean? 😄

**Comment by boltex** [comment]
This Feature has been greatly improved in branch "boltex/issue74"

**Comment by edreamleo** [comment]
Perhaps `@bool stayInTreeAfterSelect` (in leoSettings.leo) is relevant to this issue. Here are the comments:

True: (Recommended) Selecting an outline node leaves the focus in the outline pane.

If this is False it will be harder to use the arrow keys in the headline.
    
False: (Legacy) Selecting an outline node transfers focus to the body pane.
