### ISSUE TITLE
Implement commands goto 'Prev' and 'Next' nodes as shown in Leo's top toolbar

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#57]
Should be easy to do but are they a regular command(s)? or are they @buttons?

**Comment by boltex** [comment]
Maybe just make another view under the "leo outline" and "leo documents" called "leo buttons" i  guess...

Just list @buttons that leo bridge gives back when asked about it... is there a utility function in leo that gives such a list?

**Comment by edreamleo** [comment]
@boltex The nav_qt.py plugin creates these buttons.

**Comment by boltex** [comment]
Icons are in place... (they only popup 'todo' text for now) on dev branch.

**Comment by boltex** [comment]
Just discovered the c.goToPrevHistory() and c.goToNextHistory() which may make this simpler than I thought.

**Comment by edreamleo** [comment]
On Sun, Jun 27, 2021 at 7:44 PM Felix ***@***.***> wrote:

> Just discovered the c.goToPrevHistory() and c.goToNextHistory() which may
> make this simpler than I thought.
>
Oh good :-)

Edward

**Comment by boltex** [comment]
Done in branch "issue146". Works well. 

I also made a possibility to add those 2 icons on top of views in the sidebar by making commands with the same functionality to be called from the outline with buttons in the sidebar. (**_not shown yet in sidebar - will add along when doing issue #31 along with the other possible  commands._**)
