### ISSUE TITLE
Implement 'Extract' and 'Extract Name' commands

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#61]
See the 'execute script' command as an example on how to get the selection when a command is issued in order to implement the 'Extract' and 'Extract Name' commands.

**Comment by edreamleo** [comment]
I thought this might work now, but it doesn't. The problem may be that the text selection isn't passed to the command. I'll investigate.

**Comment by boltex** [comment]
This (should) depends on #39 . 
More specifically: 'Execute script', along with  'Extract' and 'Extract Name'  should instead rely on the 'save body to leo' related mechanisms of leoInteg also set its text selection range and cursor position in Leo. From that, the commander.<method> could run those commands with the expected results.
