### ISSUE TITLE
Body pane filesystem : fix timing and transition to get rid of vscode errors in debug console when de-hoisting/changing documents.

### ISSUE THREAD

**Issue by boltex** [boltex/leointeg#74]
(Does not seem to affect rendering / usage )

Providers for treeview, and provider for body pane filesystem should handle transitions from a document to the next, or hoisting/dehoisting without generating warnings/errors in vscode's debug console. 

Try to cleanup last opened-gnx transition to a new one. Also try to cleanup the tree-refresh cycle after de-hoisting/changeing leo file.

**Comment by boltex** [comment]
Redo body pane file provider to be able to give out stats from any gnx in the leo document., as timing from vscode can be tricky if user expands notes or polls leo from some info  to show parts of the tree that were refreshed from an earlier refresh call.

Might have to answer from other opened documents than the currently selected one, for example, if just switched from one document to the other.

**Comment by boltex** [comment]
**Note:** The node' id could be a double murmurhash of the "ap" json string,  https://github.com/garycourt/murmurhash-js, doubled means 64 bit  instead of 32. this would maintain node identity and replace the decorated incremented number used as of now... see https://security.stackexchange.com/questions/209882/can-a-32-bit-hash-be-made-into-a-64-bit-hash-by-calling-it-twice-with-different/210049#210049

function hash64(str) {
    var h1 = hash32(str);  // returns 32 bit (as 8 byte hex string)
    return h1 + hash32(h1 + str);  // 64 bit (as 16 byte hex string)
}

**Comment by boltex** [comment]
By using a double murmurhash of the "ap" json string,double murmurhash as id for outline nodes, **and only refreshing them (by changing salt used with hash) when operations do actually change the tree** (opposite of just navigating the tree) This will prevent refreshes and flashing/redraw.

**Comment by edreamleo** [comment]
@boltex Never heard of a murmurhash until just now. Google enlightened me. The general idea seems good.

**Comment by boltex** [comment]
Actually no need for 'Salt' at all: if the collaped state is part of the json data, the 64 (or whatever lenght) key will be different, thus refreshing the collapsed state if it changed.

**Comment by boltex** [comment]
Important: When browsing tree without changing it (navigating) having hashes for IDs will allow to use only 'reveal' method without any 'refreshes' needed at all! This will greatly benefit navigation experience!

**Comment by boltex** [comment]
**Implementation Revision:** 
Salt is incremented with tree-changing operations , but stays the same when only navigating the tree. (up down, left right,..pgup/pgdn)

Salt is also needed, depending of navigation mode, when simply navigating the tree:

1- "Standard vscode" tree navigation mode
  - change salt when collapsing / expanding, to change collapsed-state and set selection
 (consider expand/collapse to be tree changing)

2- "Leo" tree navigation mode
- dont change salt, just use reveal with the newly selected node as parameter.

**Comment by edreamleo** [comment]
@boltex Imo, this issue does not affect leoserver.py. I have removed the comment in leoserver.py.
