### ISSUE TITLE
Support syntax coloring for the languages that vs code supports

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#93]
As we discussed yesterday:

- Félix will work on the ts side.
- Edward will work on the python side.
- Edward will do his work in the "syntax" branch.

To do:

- [ ] Félix: Create a new entry in the "grammars" section of package.json for every supported language, including the "leoBody" language that describes Leonine syntax.
- [ ] Félix: Add a "leo" prefix to all patterns in syntaxes/leoBody.tmLanguage.json.
    This will ensure that there can be no clashes in pattern name between files.
- [ ] Edward: For each supported language X, create a file syntaxes/x.tmLanguage.json.

Our hope is that the typical x.tmLanguage.json file will look something like this:
```json
{
    "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    "name": "X",
    "patterns": [
        {
            "include": "#X"
        }
        {
            "include": "#leoBody"
        }
    ]
}
```
In this happy case, a Leo abbreviation will suffice. There will be no need for a script.

**Comment by boltex** [comment]
Keeping this opened as tracking and reminder to add more languages to the currently supported ones. Or for suggestions for better system.

**Comment by edreamleo** [comment]
I doubt you will get many suggestions :-) Feel free to editor or delete the to-do list in the first comment.

**Comment by boltex** [comment]
Closing this as present syntax strategy is sufficient for now - new issues will have to be opened to redo syntax coloring.
