### ISSUE TITLE
git-diff doesn't work because the working directory is not as expected

### ISSUE THREAD

**Issue by edreamleo** [boltex/leointeg#94]
Félix, in a recent email you said:

""maybe the CWD of leo/vscode is not the extension host but the original path of my other vscode window".

Perhaps this remark affects this issue.

**Comment by boltex** [comment]
Fixed in branch "boltex/issue170" by specifying a CWD to the server process when starting it from leointeg. The CWD being specifically the working dir of the current vscode workspace.
